/**
 * Shared Collection Page Component
 * 
 * Public page that displays shared content collections without requiring authentication.
 * Accessed via shareable links generated by users.
 * 
 * Features:
 * - Public access (no login required)
 * - Read-only content display
 * - Responsive masonry layout
 * - Loading and error states
 * - Owner attribution
 * - Branded header with brain icon
 * 
 * URL Pattern: /shared/:shareToken
 */

import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import { BackendURL } from '../config/config';
import { Card } from '../components/ui/Cards';
import { BrainIcon } from '../components/icons/BrainIcon';
import Masonry from "react-masonry-css";

export function SharedCollection() {
  // Extract share token from URL parameters
  const { shareToken } = useParams();
  
  // State management for shared content
  const [contents, setContents] = useState([]);      // Shared content items
  const [ownerName, setOwnerName] = useState('');    // Name of collection owner
  const [loading, setLoading] = useState(true);      // Loading state
  const [error, setError] = useState('');            // Error message

  /**
   * Fetch shared content on component mount
   * Makes API call using the share token from URL
   */
  useEffect(() => {
    const fetchSharedContent = async () => {
      try {
        // No authentication required for shared content
        const response = await axios.get(`${BackendURL}/shared/${shareToken}`);
        setContents(response.data.contents);
        setOwnerName(response.data.ownerName);
      } catch (error: any) {
        console.error('Failed to fetch shared content:', error);
        setError('Shared collection not found or no longer available.');
      } finally {
        setLoading(false);
      }
    };

    // Only fetch if share token exists
    if (shareToken) {
      fetchSharedContent();
    }
  }, [shareToken]);

  /**
   * Responsive breakpoints for masonry layout
   * Same configuration as Home page for consistency
   */
  const breakpointColumns = {
    default: 4,
    1400: 3,
    1100: 2,
    700: 1,
    500: 1,
  };

  // Loading State - shown while fetching data
  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-white flex items-center justify-center">
        <div className="text-center">
          <div className="flex justify-center mb-4">
            <BrainIcon className="w-16 h-16 text-secondary animate-pulse" />
          </div>
          <div className="text-xl font-serif text-slate-700">Loading shared collection...</div>
          <div className="w-24 h-1 bg-gradient-to-r from-purple-600 to-blue-600 mx-auto rounded-full mt-3"></div>
        </div>
      </div>
    );
  }

  // Error State - shown when collection not found or other errors
  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-white flex items-center justify-center">
        <div className="text-center max-w-md mx-4">
          <div className="flex justify-center mb-6">
            <BrainIcon className="w-20 h-20 text-slate-400" />
          </div>
          <h1 className="text-3xl font-serif font-bold text-slate-800 mb-4">Oops!</h1>
          <p className="text-slate-600 text-lg mb-6">{error}</p>
          <div className="w-16 h-1 bg-slate-300 mx-auto rounded-full"></div>
        </div>
      </div>
    );
  }

  // Main Content - shown when data loads successfully
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-white">
      
      {/* Header Section - displays owner info and branding */}
      <div className="bg-gradient-to-r from-white to-slate-50 border-b border-slate-200 shadow-lg">
        <div className="container mx-auto px-6 py-8">
          <div className="text-center">
            {/* Brain Icon Branding */}
            <div className="flex justify-center mb-4">
              <BrainIcon className="w-12 h-12 text-secondary"/>
            </div>
            
            {/* Collection Title with Owner Attribution */}
            <h1 className="text-4xl font-serif font-bold mb-2">
              <span className="bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                {ownerName}'s
              </span>
              <span className="text-slate-800 ml-2">Second Brain</span>
            </h1>
            
            {/* Read-only indicator */}
            <p className="text-slate-600 text-lg">Shared collection • Read only</p>
            <div className="w-24 h-1 bg-gradient-to-r from-purple-600 to-blue-600 mx-auto rounded-full mt-4"></div>
          </div>
        </div>
      </div>

      {/* Content Section */}
      <div className="container mx-auto px-6 py-8">
        {contents.length === 0 ? (
          // Empty State - shown when collection has no content
          <div className="text-center py-16">
            <div className="flex justify-center mb-6">
              <BrainIcon className="w-16 h-16 text-slate-400" />
            </div>
            <h2 className="text-2xl font-serif font-bold text-slate-700 mb-2">Empty Collection</h2>
            <p className="text-slate-500 text-lg">This brain hasn't been fed yet!</p>
          </div>
        ) : (
          // Content Grid - masonry layout for shared content
          <>
            <Masonry
              breakpointCols={breakpointColumns}
              className="flex w-full -ml-1"
              columnClassName="masonry-column pl-1"
            >
              {contents.map(({ _id, types, link, title, tags }, index) => (
                <Card
                  id={_id}
                  key={index}
                  title={title}
                  contentType={types}
                  link={link}
                  tags={tags}
                  onSuccessDelete={() => {}} // No delete functionality for shared view
                  readOnly={true}           // Disable delete button
                />
              ))}
            </Masonry>
          </>
        )}
      </div>
    </div>
  );
}